spring:
  application:
    name: center-service
  profiles:
    active: ${PROFILE_ACTIVES:prod}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: INFO
    web: debug

    com.zaxxer.hikari: warn
