server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
#    whitelabel:
#      enabled: false
#  forward-headers-strategy: native

spring:
  application:
    name: center-service
  profiles:
    active: ${PROFILE_ACTIVES:dev}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
#    csrf:
#      enabled: false
  packages-to-scan: com.cbs.center_service.controllers
  show-actuator: true

scalar:
  enabled: false
  actuatorEnabled: true
  path: /scalar
  url: /v3/api-docs
  theme: bluePlanet
  layout: modern

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: INFO
    web: debug
    org:
      springdoc: debug
    com:
      scalar: debug

    com.zaxxer.hikari: warn